name: TogglePvP
version: ${project.version}
main: com.mctng.togglepvp.TogglePvP
api-version: 1.13
authors: [Worf2340]
description: A plugin to toggle PvP per player.
website: www.mctng.com


commands:
  healme:
    description: Healing command
    usage: /healme
  togglepvp:
    description: Toggle PvP for a player
    usage: /togglepvp [player] [on/off] <duration(h/m)>
  pvpstatus:
    description: Check PvP Status of a player
    usage: /pvpstatus <player>

permissions:
  togglepvp.pvpstatus.others:
    description: Check pvp status of other players
    default: op
